version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "7777:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3309:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


