# Generated by Django 4.2.6 on 2023-10-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='group',
            new_name='related_group',
        ),
    ]
