# Generated by Django 4.2.6 on 2023-10-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0003_rename_group_usermodel_related_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='groups.groupmodel'),
        ),
    ]
