# Generated by Django 4.2.6 on 2023-10-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0005_alter_usermodel_related_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='related_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='groups.groupmodel'),
        ),
    ]
